### ISSUE TITLE
[DOCS] Installation without composer and typo3 v9

### ISSUE THREAD

**Issue by gregordonsky** [studiomitte/sendinblue#1]
Just a note for reporting my experience.
I tryed to install this extension on typo3 v9.5.26 without composer and seems that everything is working correctly.

Here you are the instructions:
1) Download the package v 7.3 of  [https://github.com/sendinblue/APIv3-php-library](https://github.com/sendinblue/APIv3-php-library)
2) Create a folder in this sendinblue extension named `api-v3-sdk`. Copy into the folder the content of SendinBlue's API package
3) In ext_emconf.php add these lines:

```php
    'autoload' => [
        'psr-4' => [
            'StudioMitte\\Sendinblue\\' => 'Classes',
            'SendinBlue\\Client\\' => 'api-v3-sdk/lib',
        ],
    ],
```
4) `Dump autolad` and `clean the cache` into typo3 maintenance section

**Comment by georgringer** [comment]
thanks for the information!
